// Modal
export const SET_ACTIVE_MODAL = 'SET_ACTIVE_MODAL';
export const HIDE_ACTIVE_MODAL = 'HIDE_ACTIVE_MODAL';

export const SHOW_CONFIRM_MODAL = 'SHOW_CONFIRM_MODAL';
export const HIDE_CONFIRM_MODAL = 'HIDE_CONFIRM_MODAL';
